### ISSUE TITLE
avoid use of project monikers

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/OhdsiRTools#1]
as a general guideline we're trying to avoid using the greek project names so instead of 

insertCirceDefinitionInPackage(123, "MyocardialInfarction")

perhaps 

insertCohortDefinitionInPackage(123,"MyocardialInfarction")

**Comment by schuemie** [comment]
Changed the function name, deprecated the old one: 208a60376f99663e579c3a51ee1599598e5207cf
