### ISSUE TITLE
Should baseURL follow the rule of .checkBaseUrl ?

### ISSUE THREAD

**Issue by chandryou** [OHDSI/OhdsiRTools#16]
I'm try to execute 'OhdsiRTool::insertCohortDefinitionSetInPackage'
And I'm suffering from '.checkBaseUrl'

```
.checkBaseUrl <- function(baseUrl)
  {
    return(grepl(pattern = "https?:\\/\\/[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})+(\\/.*)?\\/WebAPI$", 
                 x = baseUrl, 
                 ignore.case = FALSE))
  }
```

My WebAPI address looks like this:' http://128.1.99.100:8080/WebAPI'
It doesn't work because '**[a-z]{2,5}**'

Should baseURL follow the rule of .checkBaseUrl ??

Thank you!

**Comment by alondhe** [comment]
Hi @chandryou -- we should edit this rule for IPs like yours where there is no dot com or dot <something>. 

Messing with regex, perhaps we add a 2nd regex string?

`https?:\/\/(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(:[0-9]{1,5})+(\/.*)?\/WebAPI$`

**Comment by alondhe** [comment]
@chandryou can you try my forked version: https://github.com/alondhe/OhdsiRTools

**Comment by chandryou** [comment]
It works perfectly! Thank you, @alondhe 
Could you modify this repo, too?
