### ISSUE TITLE
New WebAPI functions to support CDM/Vocab versioning comparisons

### ISSUE THREAD

**Issue by alondhe** [OHDSI/OhdsiRTools#21]
@fdefalco and I have been discussing adding a few new functions to help evaluate the impact of CDM or vocabulary changes on a cohort. 

For transparency, here they are. I'll make a PR soon.

1. resolve concept sets based on a concept set expression (can refactor the current getConceptSetConceptIds function)
2. get a cohort expression json (can refactor the current insertCohortDefinitionInPackage function)
3. get cohort definition sql
4. get cohort definition concepts

**Comment by schuemie** [comment]
Sounds good!

Perhaps we should start thinking about creating a separate RWebApi package? (Or 'WebApiR')

**Comment by alondhe** [comment]
Is that because these functions are falling out of scope, or simply to ensure we don't have too many functions in one package?

**Comment by schuemie** [comment]
The 'scope' of OhdsiRTools is 

> An R package of support tools that didn’t fit other categories

Sounds like "R functions for interacting with WebApi" is a nice coherent self-contained category that deserves its own package :-)

 Having a separate package might be clearer to users, and would require less dependencies than [this oddball list](https://github.com/OHDSI/OhdsiRTools/blob/master/DESCRIPTION#L19) to run WebApi calls.

**Comment by alondhe** [comment]
Makes sense! Can you create a new repo? I can start shifting over the functions

**Comment by schuemie** [comment]
Any preference for the name? We could do RWebApi, WebApiR, or maybe ROhdsiWebApi to distinguish it from other web API packages?

This may also be a good time to look at what others have done in similar situations. There's even [a CRAN document on best practices for creating API R packages](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html)

**Comment by alondhe** [comment]
That document didn't mention anything specifically for naming these packages, but googling around, I do think we should try to avoid collisions with other R packages that provide web API functions. 

So, ROhdsiWebApi may be safest, though a bit clunky. @fdefalco curious about your thoughts.
