### ISSUE TITLE
cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.5/PACKAGES'

### ISSUE THREAD

**Issue by yamsania** [OHDSI/OhdsiRTools#28]
followed the installation instructions but receiving the following error.

Warning in install.packages :
  unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.5:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.5/PACKAGES'

   package ‘OhdsiRTools’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘OhdsiRTools’ is not available (as a binary package for R version 3.5.2)

**Comment by yamsania** [comment]
Checked if Rtools is installed and it is.

**Comment by schuemie** [comment]
It is just a warning saying there's no binary version. It should automatically proceed to install the source package. Does it not do that?

**Comment by yamsania** [comment]
Unfortunately, it does not. It just stops there. I actual intent is to install Achilles and seems like i am having problem there as well. 

Downloading GitHub repo OHDSI/Achilles@7ab34ba
Installing 22 packages: DatabaseConnector, SqlRender, dplyr, rjson, ParallelLogger, bit, ff, fastmatch, triebeard, lifecycle, pillar, pkgconfig, vctrs, utf8, ffbase, DBI, urltools, tibble, tidyselect, plogr, snow, XML
Installing packages into ‘Z:/SFR/Achillies/packrat/lib/x86_64-w64-mingw32/3.5.2’
(as ‘lib’ is unspecified)
Error: Failed to install 'Achilles' from GitHub:
  (converted from warning) unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.5:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.5/PACKAGES'

**Comment by yamsania** [comment]
@schuemie with little more experimentation figured it out that it was environmental issue, we removed the the R we had and reinstalled it from scratch with latest version and it started working as expected!
